#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Tue Aug 19 23:00:17 2014
#

import wx

# begin wxGlade: dependencies
import gettext
import visual_mol_method as vm
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        self.atom_no_1 = 1;
        self.atom_no_2 = 1;
        self.log = 0;
        self.z_pos = 0;
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.Mol_label = wx.StaticText(self.panel_1, wx.ID_ANY, _("分子"))
        self.mol_box = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[_("水素")], style=wx.CB_READONLY)
        self.Coor1_label = wx.StaticText(self.panel_1, wx.ID_ANY, _("原子座標1(x,y,z)"))
        self.coor1_x = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.coor1_y = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.coor1_z = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.Coor2_label = wx.StaticText(self.panel_1, wx.ID_ANY, _("原子座標2(x,y,z)"))
        self.coor2_x = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.coor2_y = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.coor2_z = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.Bf_label = wx.StaticText(self.panel_1, wx.ID_ANY, _("基底関数"))
        self.Bf_box = wx.ComboBox(self.panel_1, wx.ID_ANY, "sto-3g",choices=[("sto-3g"), ("6-31g"), ("3-21g"),("6-31g**"),("6-31g**++"),("6-311g**"),("sto-6g"),("cc-pvdz"),("cc-pvtz"),("dzvp"),("6-311g++(2d,2p)"),("6-311g++(3d,3p)"),("6-311g++(3df,3pd)")], style=wx.CB_READONLY) 
        #self.orb_bound = wx.StaticText(self.panel_1, wx.ID_ANY, _("結合性軌道/反結合性軌道"))
        #self.orb_bound_box = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[_("結合性軌道"), _("反結合性軌道")], style=wx.CB_DROPDOWN)
        self.z_pos_label = wx.StaticText(self.panel_1, wx.ID_ANY, _("Z position"))
        self.z_pos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "0.0")
        self.LoggingBox = wx.CheckBox(self.panel_1, wx.ID_ANY, _("ログ(calc.log)"))
        self.default_bt = wx.Button(self.panel_1, wx.ID_ANY, _("Example"))
        self.calculate_bt = wx.Button(self.panel_1, wx.ID_ANY, _("Calculate"))
        self.visual_bt = wx.Button(self.panel_1, wx.ID_ANY, _("出力"))
        self.console_box = wx.TextCtrl(self, wx.ID_ANY, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_COMBOBOX,self.SetMolecule,self.mol_box)
        self.Bind(wx.EVT_CHECKBOX,self.logbox,self.LoggingBox)       
        self.Bind(wx.EVT_BUTTON, self.Default, self.default_bt)
        self.Bind(wx.EVT_BUTTON, self.Calculate, self.calculate_bt)
        self.Bind(wx.EVT_BUTTON, self.Visualize, self.visual_bt)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("Visualize Molecule"))
        self.mol_box.SetSelection(0)
        self.coor1_x.SetMinSize((140, 27))
        self.coor1_y.SetMinSize((140, 27))
        self.coor1_z.SetMinSize((140, 27))
        self.coor2_x.SetMinSize((140, 27))
        self.coor2_y.SetMinSize((140, 27))
        self.coor2_z.SetMinSize((140, 27))
        self.Bf_box.SetSelection(0)
        #self.orb_bound_box.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(7, 4, 0, 0)
        grid_sizer_1.Add(self.Mol_label, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.mol_box, 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add((20, 20), 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.Coor1_label, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.coor1_x, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.coor1_y, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.coor1_z, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.Coor2_label, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.coor2_x, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.coor2_y, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.coor2_z, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.Bf_label, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.Bf_box, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        #grid_sizer_1.Add(self.orb_bound, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        #grid_sizer_1.Add(self.orb_bound_box, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.z_pos_label, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.z_pos, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add((20, 20), 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add((20, 20), 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.LoggingBox, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 9)
        grid_sizer_1.Add(self.default_bt, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.calculate_bt, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.visual_bt, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        self.panel_1.SetSizer(grid_sizer_1)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(self.console_box, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def Default(self, event):  # wxGlade: MyFrame.<event_handler>
        vm.default(self)
        event.Skip()

    def Calculate(self, event):  # wxGlade: MyFrame.<event_handler>
        vm.calculate(self)
        event.Skip()

    def Visualize(self, event):  # wxGlade: MyFrame.<event_handler>
        vm.visualize(self)
        event.Skip()
    
    def SetMolecule(self, event):
        vm.setmolecule(self)
        event.Skip()

    def logbox(self, event):
        self.log = 1
        event.Skip()

# end of class MyFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
